# Copyright (c) 1991-2013 Kawahara Lab., Kyoto University
# Copyright (c) 1997-2000 Information-technology Promotion Agency, Japan
# Copyright (c) 2000-2005 Shikano Lab., Nara Institute of Science and Technology
# Copyright (c) 2005-2013 Julius project team, Nagoya Institute of Technology
# All rights reserved

#
# $Id: Makefile.in,v 1.11 2013/06/20 17:14:18 sumomo Exp $
#
SHELL=/bin/sh
.SUFFIXES:
.SUFFIXES: .c .o
.c.o:
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $@ -c $<

LIBSENT=../../libsent
LIBJULIUS=../../libjulius
CC=/home/takahiro/document/source/emscripten/emcc
CFLAGS= -I../FFmpeg-emscripten/ -I../FFmpeg-emscripten/emffmpeglib -I../FFmpeg-emscripten/libavformat -I../FFmpeg-emscripten/fftools -O3 -s --js-opts 1 -s -flto -s WASM=1 -s ASYNCIFY=1 -s NO_EXIT_RUNTIME=1 -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=268435456 -s MAXIMUM_MEMORY=2097152000 -s WASM_MEM_MAX=2097152000 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s EXPORT_ALL=1 -s "EXPORTED_FUNCTIONS=['_file_uploaded']" -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" -s FORCE_FILESYSTEM=1 --preload-file am-gmm.jconf --preload-file main.jconf --preload-file wav_config --preload-file jnas-mono-16mix-gid.binhmm --preload-file jnas-mono-16mix-gid.hmmdefs --preload-file jnas-tri-3k16-gid.binhmm --preload-file jnas-tri-3k16-gid.hmmdefs --preload-file jnas-tri-rtree.base --preload-file jnas-tri-rtree.tree --preload-file logicalTri --preload-file logicalTri-3k16-gid.bin --preload-file bccwj.60k.bingram --preload-file bccwj.60k.htkdic --preload-file bccwj.60k.pdp.htkdic
CPPFLAGS= -I. -I$(LIBJULIUS)/include -I$(LIBSENT)/include  `$(LIBSENT)/libsent-config --cflags` `$(LIBJULIUS)/libjulius-config --cflags`
LDFLAGS= -L$(LIBJULIUS) `$(LIBJULIUS)/libjulius-config --libs` -L$(LIBSENT) `$(LIBSENT)/libsent-config --libs` ../FFmpeg-emscripten/libavcodec/libavcodec.a ../FFmpeg-emscripten/libavutil/libavutil.a ../FFmpeg-emscripten/libavformat/libavformat.a ../FFmpeg-emscripten/libavfilter/libavfilter.a ../FFmpeg-emscripten/libavdevice/libavdevice.a ../FFmpeg-emscripten/libswresample/libswresample.a ../FFmpeg-emscripten/libswscale/libswscale.a
GTK_CFLAGS=
GTK_LIBS=
RM=/bin/rm -f

## install
prefix=/usr/local
exec_prefix=${prefix}
bindir=${exec_prefix}/bin
libdir=${exec_prefix}/lib
includedir=${prefix}/include
mandir=${prefix}/share/man
INSTALL=/usr/bin/install -c
INSTALL_DATA=${INSTALL} -m 644
INSTALL_PROGRAM=${INSTALL}

############################################################

TARGET = index.js
INSTALLTARGET = julius

OBJ = \
main.c \
recogloop.o \
module.o \
output_module.o \
output_stdout.o \
output_file.o \
record.o \
charconv.o charconv_iconv.o \
../FFmpeg-emscripten/emffmpeglib/ffmpeg.c ../FFmpeg-emscripten/fftools/cmdutils.o ../FFmpeg-emscripten/fftools/ffmpeg_opt.o ../FFmpeg-emscripten/fftools/ffmpeg_hw.o ../FFmpeg-emscripten/fftools/ffmpeg_filter.o

############################################################

all: $(TARGET)

$(TARGET): $(LIBSENT)/libsent.a $(LIBJULIUS)/libjulius.a $(OBJ)
	$(CC) $(CFLAGS) $(CPPFLAGS) -o bin/$@ $(OBJ) $(LDFLAGS) $(GTK_LIBS)

############################################################

install: install.bin

install.bin: $(TARGET)
	${INSTALL} -d ${exec_prefix}/bin
	${INSTALL_PROGRAM} $(TARGET) ${bindir}/${INSTALLTARGET}

depend:
	makedepend -- $(CFLAGS) -- $(OBJSENT)

smallclean:
	$(RM) *.o

clean:
#	$(RM) *.o *.bak *~ core TAGS
	$(RM) $(OBJ)
	$(RM) *.bak *~ core TAGS
	$(RM) config.log config.cache
	$(RM) $(TARGET) $(INSTALLTARGET)
	$(RM) $(TARGET).exe $(INSTALLTARGET).exe

distclean:
#	$(RM) *.o *.bak *~ core TAGS
	$(RM) $(OBJ)
	$(RM) *.bak *~ core TAGS
	$(RM) config.log config.cache
	$(RM) $(TARGET) $(INSTALLTARGET)
	$(RM) $(TARGET).exe $(INSTALLTARGET).exe
	$(RM) config.status config.h
	$(RM) Makefile

############################################################
configure:
	autoconf
	$(RM) config.h.in
	autoheader
