rm ./doc/print_options.o
#rm ./libavutil/aarch64/float_dsp_init.o
#rm ./libavutil/aarch64/cpu.o
#rm ./libavutil/aarch64/float_dsp_neon.o
rm ./libavutil/log2_tab.o
rm ./libavutil/reverse.o
rm ./libavcodec/v4l2_buffers.o
rm ./libavcodec/flashsv.o
rm ./libavcodec/mwsc.o
rm ./libavcodec/pthread_slice.o
rm ./libavcodec/flashsv2enc.o
rm ./libavcodec/zmbvenc.o
rm ./libavcodec/wma_common.o
rm ./libavcodec/wmv2data.o
rm ./libavcodec/v4l2_m2m_enc.o
rm ./libavcodec/mqc.o
rm ./libavcodec/exr.o
rm ./libavcodec/wcmv.o
rm ./libavcodec/cga_data.o
rm ./libavcodec/dxa.o
rm ./libavcodec/rasc.o
rm ./libavcodec/rscc.o
rm ./libavcodec/flashsvenc.o
rm ./libavcodec/zmbv.o
rm ./libavcodec/mqcdec.o
rm ./libavcodec/exrdsp.o
rm ./libavcodec/mpegvideodata.o
rm ./libavcodec/pngdec.o
rm ./libavcodec/wma_freqs.o
rm ./libavcodec/frame_thread_encoder.o
rm ./libavcodec/proresdata.o
rm ./libavcodec/png.o
rm ./libavcodec/diractab.o
rm ./libavcodec/pngdsp.o
rm ./libavcodec/screenpresso.o
rm ./libavcodec/pthread.o
rm ./libavcodec/mvha.o
#rm ./libavcodec/aarch64/rv40dsp_init_aarch64.o
#rm ./libavcodec/aarch64/h264dsp_neon.o
#rm ./libavcodec/aarch64/vp9dsp_init_12bpp_aarch64.o
#rm ./libavcodec/aarch64/videodsp.o
#rm ./libavcodec/aarch64/mpegaudiodsp_init.o
#rm ./libavcodec/aarch64/pixblockdsp_neon.o
#rm ./libavcodec/aarch64/vorbisdsp_neon.o
#rm ./libavcodec/aarch64/sbrdsp_neon.o
#rm ./libavcodec/aarch64/h264pred_init.o
#rm ./libavcodec/aarch64/h264pred_neon.o
#rm ./libavcodec/aarch64/vp9itxfm_neon.o
#rm ./libavcodec/aarch64/vp9mc_aarch64.o
#rm ./libavcodec/aarch64/pixblockdsp_init_aarch64.o
#rm ./libavcodec/aarch64/synth_filter_init.o
#rm ./libavcodec/aarch64/idctdsp_init_aarch64.o
#rm ./libavcodec/aarch64/fmtconvert_neon.o
#rm ./libavcodec/aarch64/h264idct_neon.o
#rm ./libavcodec/aarch64/vp9dsp_init_aarch64.o
#rm ./libavcodec/aarch64/vp9itxfm_16bpp_neon.o
#rm ./libavcodec/aarch64/h264qpel_neon.o
#rm ./libavcodec/aarch64/vp9lpf_16bpp_neon.o
#rm ./libavcodec/aarch64/vp9lpf_neon.o
#rm ./libavcodec/aarch64/hpeldsp_init_aarch64.o
#rm ./libavcodec/aarch64/mpegaudiodsp_neon.o
#rm ./libavcodec/aarch64/opusdsp_neon.o
#rm ./libavcodec/aarch64/h264chroma_init_aarch64.o
#rm ./libavcodec/aarch64/fft_neon.o
#rm ./libavcodec/aarch64/fft_init_aarch64.o
#rm ./libavcodec/aarch64/opusdsp_init.o
#rm ./libavcodec/aarch64/synth_filter_neon.o
#rm ./libavcodec/aarch64/mdct_neon.o
#rm ./libavcodec/aarch64/simple_idct_neon.o
#rm ./libavcodec/aarch64/vp8dsp_neon.o
#rm ./libavcodec/aarch64/aacpsdsp_init_aarch64.o
#rm ./libavcodec/aarch64/vp9dsp_init_10bpp_aarch64.o
#rm ./libavcodec/aarch64/vp9mc_16bpp_neon.o
#rm ./libavcodec/aarch64/videodsp_init.o
#rm ./libavcodec/aarch64/vp8dsp_init_aarch64.o
#rm ./libavcodec/aarch64/vp9mc_neon.o
#rm ./libavcodec/aarch64/vc1dsp_init_aarch64.o
#rm ./libavcodec/aarch64/hpeldsp_neon.o
#rm ./libavcodec/aarch64/fmtconvert_init.o
#rm ./libavcodec/aarch64/h264dsp_init_aarch64.o
#rm ./libavcodec/aarch64/sbrdsp_init_aarch64.o
#rm ./libavcodec/aarch64/aacpsdsp_neon.o
#rm ./libavcodec/aarch64/h264qpel_init_aarch64.o
#rm ./libavcodec/aarch64/h264cmc_neon.o
#rm ./libavcodec/aarch64/vorbisdsp_init.o
rm ./libavcodec/elsdec.o
rm ./libavcodec/pthread_frame.o
rm ./libavcodec/pngenc.o
rm ./libavcodec/v4l2_context.o
rm ./libavcodec/dvdata.o
rm ./libavcodec/on2avcdata.o
rm ./libavcodec/tscc.o
rm ./libavcodec/hevc_data.o
rm ./libavcodec/g2meet.o
rm ./libavcodec/mscc.o
rm ./libavcodec/aandcttab.o
rm ./libavcodec/v4l2_m2m_dec.o
rm ./libavcodec/v4l2_m2m.o
rm ./libavcodec/mpeg12data.o
rm ./libavcodec/tdsc.o
rm ./libavcodec/lclenc.o
rm ./libavcodec/v4l2_fmt.o
rm ./libavcodec/neon/mpegvideo.o
rm ./libavcodec/zerocodec.o
#rm ./libswresample/aarch64/audio_convert_neon.o
#rm ./libswresample/aarch64/resample.o
#rm ./libswresample/aarch64/audio_convert_init.o
#rm ./libswresample/aarch64/resample_init.o
rm ./libavfilter/pthread.o
rm ./libavfilter/aarch64/vf_nlmeans_neon.o
rm ./libavfilter/aarch64/vf_nlmeans_init.o
rm ./libavformat/fifo.o
rm ./libavformat/sctp.o
rm ./libavformat/async.o
rm ./libavdevice/sndio_dec.o
rm ./libavdevice/timefilter.o
rm ./libavdevice/v4l2-common.o
rm ./libavdevice/sndio_enc.o
rm ./libavdevice/fbdev_common.o
rm ./libavdevice/v4l2enc.o
rm ./libavdevice/v4l2.o
rm ./libavdevice/oss.o
rm ./libavdevice/fbdev_dec.o
rm ./libavdevice/alsa.o
rm ./libavdevice/fbdev_enc.o
rm ./libavdevice/oss_enc.o
rm ./libavdevice/xv.o
rm ./libavdevice/xcbgrab.o
rm ./libavdevice/alsa_dec.o
rm ./libavdevice/oss_dec.o
rm ./libavdevice/sndio.o
rm ./libavdevice/alsa_enc.o
#rm ./libswscale/aarch64/swscale_unscaled.o
#rm ./libswscale/aarch64/hscale.o
#rm ./libswscale/aarch64/rgb2rgb.o
#rm ./libswscale/aarch64/yuv2rgb_neon.o
#rm ./libswscale/aarch64/swscale.o
#rm ./libswscale/aarch64/output.o
#rm ./libswscale/aarch64/rgb2rgb_neon.o
